---
#
# Ansible managed
#
repository:
  description: An ansible role for managing mail aliases.
  homepage: https://buluma.github.io/
  topics: aliases, ansible, molecule, tox, playbook, hacktoberfest
