---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify
      ansible.builtin.shell: which newaliases && newaliases || true
      register: my_output
      changed_when: my_output.rc != 0
